// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU5gB4e_jTl-Z5XB1shna-LAFL2HqW4gM',
    appId: '1:1020345771219:web:4fe4b8016e49d7801d2026',
    messagingSenderId: '1020345771219',
    projectId: 'foto-app-bb05d',
    authDomain: 'foto-app-bb05d.firebaseapp.com',
    storageBucket: 'foto-app-bb05d.appspot.com',
    measurementId: 'G-ZTD1X8PY0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3qYhAEpEOvgjfekCGUZE39mpS4JkQCKA',
    appId: '1:1020345771219:android:69e6da727ce0e6e01d2026',
    messagingSenderId: '1020345771219',
    projectId: 'foto-app-bb05d',
    storageBucket: 'foto-app-bb05d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoZbID4hx9auWMCcYUGBd-w_tyid-jd8s',
    appId: '1:1020345771219:ios:bd103288a8b383eb1d2026',
    messagingSenderId: '1020345771219',
    projectId: 'foto-app-bb05d',
    storageBucket: 'foto-app-bb05d.appspot.com',
    iosClientId: '1020345771219-o4ao2qlsvcsq7nlpkej4a2lpu1ickkt9.apps.googleusercontent.com',
    iosBundleId: 'com.example.fotoapp',
  );
}
